version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh /app/entrypoint.sh poetry run python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    restart: "on-failure"
    depends_on:
      - postgres-db
    networks:
      - geodjango-web

  postgres-db:
    image: imresamu/postgis
    platform: linux/arm64
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    env_file:
      - .env
    restart: "on-failure"
    networks:
      - geodjango-web
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DBNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    restart: always
    depends_on:
      - web
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 8080:80
    networks:
      - geodjango-web

networks:
  geodjango-web:
    driver: bridge

volumes:
  postgres_data:
